# Generated by Django 2.2.4 on 2019-08-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alojadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion_cot', models.IntegerField()),
                ('tamano', models.IntegerField()),
            ],
            options={
                'db_table': 'alojadores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cinta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('tipo', models.CharField(blank=True, max_length=4, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'cinta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_asuth', models.IntegerField()),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('razon', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'movimiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UbicacionCinta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.IntegerField()),
            ],
            options={
                'db_table': 'ubicacion_cinta',
                'managed': False,
            },
        ),
    ]
